### ISSUE TITLE
Major To-Do

### ISSUE THREAD

**Issue by sauravkhdoolia** [yabwe/medium-editor#1552]
### Major To-Do

These are major tasks which needs to be done ASAP. Will be adding new ones.

- [ ] Migrating form Sauce Labs to Browser Stack
- [ ] Migrating from Jasmine to Mocha or Something like that as Jasmine is getting older
- [ ] Migrating from Grunt to other Task runner, Probably RollUp.

These are a must to get the project moving as we'll need more robust testing and overall dev env.

**Comment by sauravkhdoolia** [comment]
@arteconceito Add anything else you want.

**Comment by arteconceito** [comment]
@sauravkhdoolia Will have a look at it later, I must atend something else now. Thanks for the tip, will follow up on it :+1:

**Comment by daesdev** [comment]
### Update  Major TO-DO

These are major tasks that need to be done ASAP. Will be adding new ones.

Thoughts and Suggestions are welcome.

### Highest P
  - [x] Getting the tests to pass.
  - [x] Migrating from Sauce Labs to Browser Stack
### High P
  - [ ] Resolve issues [334 Opens]
  - [ ] Merge Selected PRs [26 Open]
  - [ ] Resolve TODOs for v6.0 in the Project
### Low P
  - [ ] Rewrite
  - [ ] JS -> TS
  - [ ] IIFE -> ES6 Modules!

 - [ ] Migrating from Grunt to other Task runners, Probably Roll-Up.

These are a must to get the project moving as we'll need more robust testing and overall dev env.
